### ISSUE TITLE
Crash goal isn't awarded when it should be

### ISSUE THREAD

**Issue by rrenaud** [rrenaud/dominionstats#7]
http://councilroom.com/game?game_id=game-20110929-211349-840b33dd.html

**Comment by goober82** [comment]
Similar issue here: 

http://councilroom.com/game?game_id=game-20110417-180433-e53e02f1.html

In the game log, the charge badge appears, but it does not show up on my player page with all the other badges.

**Comment by rrenaud** [comment]
I think the 'doesn't show up on player page' problem is because I am keying the badges by game id, and so there can only be one badge per game.  I'll probably fix it eventually, but it isn't totally trivial, because it requires changing the reader and writer.

**Comment by rrenaud** [comment]
Fixed thanks to David Lu.  Yay ;).
