### ISSUE TITLE
VP Miscalculations

### ISSUE THREAD

**Issue by shikexue** [rrenaud/dominionstats#8]
In goals.py, you calculate each duchy as 5 points for the duke of earl achievement. The code says

duchy_pts = deck['Duchy'] \* 5

**Comment by shikexue** [comment]
Another miscalculation bug: 
In the little strip at the bottom which keeps track of points and cards, Fairgrounds is consistently being overvalued; by the end of the game, it is calculated at 7VP instead of 6:
http://councilroom.com/game?game_id=game-20110628-002654-1d742fa6.html

**Comment by shikexue** [comment]
http://councilroom.com/game?game_id=game-20111007-175905-c674a66e.html

6 Gardens at 59 cards should be 30 VP, not 24 as the text for the goal at the bottom would indicate.

Also, in this game:
http://councilroom.com/game?game_id=game-20111004-180310-5df8fc49.html

VP Tokens gained during a possessed turns aren't added in the bar at the bottom, and so it shows the wrong player winning in the bottom bar.

**Comment by rrenaud** [comment]
Thanks, I think I've fixed this.
